name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Préparer MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compiler le moteur C++
        run: |
          cl /O2 /EHsc /std:c++17 hexalign.cpp /Fe:hexalign.exe

      - name: Installer les dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Créer l'exécutable
        run: |
          pyinstaller --onefile --windowed --name QIAnalyse --add-binary "hexalign.exe;." main.py

      - name: Publier l'exe
        uses: actions/upload-artifact@v4
        with:
          name: QIAnalyse-Windows
          path: dist/QIAnalyse.exe
